"""add guid fields to file_compare

Revision ID: 0b36e9110e0d
Revises: 830ea5888a9d
Create Date: 2024-12-12 20:49:07.426217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b36e9110e0d'
down_revision: Union[str, None] = '830ea5888a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_compare', sa.Column('f_file_guid', sa.Text(), nullable=True))
    op.add_column('file_compare', sa.Column('s_file_guid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_compare', 's_file_guid')
    op.drop_column('file_compare', 'f_file_guid')
    # ### end Alembic commands ###
