"""initial

Revision ID: 830ea5888a9d
Revises: 
Create Date: 2024-12-12 20:32:43.263256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830ea5888a9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_process',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('process_task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_extraction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fact_name', sa.Text(), nullable=True),
    sa.Column('fact_localization', sa.Text(), nullable=True),
    sa.Column('fact_value', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('file_process_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['file_process_id'], ['file_process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_compare',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('f_file_name', sa.Text(), nullable=True),
    sa.Column('s_file_name', sa.Text(), nullable=True),
    sa.Column('f_file_process_id', sa.BigInteger(), nullable=True),
    sa.Column('s_file_process_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['f_file_process_id'], ['file_process.id'], ),
    sa.ForeignKeyConstraint(['s_file_process_id'], ['file_process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('json_result', sa.Text(), nullable=True),
    sa.Column('file_process_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['file_process_id'], ['file_process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('probability', sa.Double(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('top', sa.Double(), nullable=True),
    sa.Column('left', sa.Double(), nullable=True),
    sa.Column('width', sa.Double(), nullable=True),
    sa.Column('height', sa.Double(), nullable=True),
    sa.Column('fact_extraction_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['fact_extraction_id'], ['fact_extraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_info')
    op.drop_table('process_result')
    op.drop_table('file_compare')
    op.drop_table('fact_extraction')
    op.drop_table('file_process')
    # ### end Alembic commands ###
